test:
  # Credentials for REST APIs
  client_id: <%= ENV['PAYPAL_CLIENT_ID'] %>
  client_secret: <%= ENV['PAYPAL_SECRET'] %>

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

development:
  # Credentials for REST APIs
  client_id: <%= ENV['PAYPAL_CLIENT_ID'] %>
  client_secret: <%= ENV['PAYPAL_SECRET'] %>

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

production:
  # Credentials for REST APIs
  client_id: <%= ENV['PAYPAL_CLIENT_ID'] %>
  client_secret: <%= ENV['PAYPAL_SECRET'] %>

  # Mode can be 'live' or 'sandbox'
  mode: sandbox
